export const TEST_IDS = {
  homeScreen: "home-screen",
  volcanoesHeading: "volcanoes-heading",
  inferenceDeformationButton: "inference-deformation-button",
  inferenceSeismicButton: "inference-seismic-button",
  homeMap: "home-map",
  volcanoPopup: "volcano-popup",
  openAdminLink: "open-admin-link",
  createProfileLink: "create-profile-link",
  myProfileButton: "my-profile-button",
  myProfileDialog: "my-profile-dialog",
  myProfileCloseButton: "my-profile-close-button",
  myProfileNameField: "my-profile-name-field",
  myProfileEmailField: "my-profile-email-field",
  adminScreen: "admin-screen",
  backToDashboardLink: "back-to-dashboard-link",
  modelsHeading: "models-heading",
  ingestButton: "ingest-button",
  refineButton: "refine-button",
  trainButton: "train-button",
  batchButton: "batch-button",
  promoteButton: "promote-button",
  refreshButton: "refresh-button",
  maxSamplesField: "max-samples-field",
  sourceField: "source-field",
  stageField: "stage-field",
  signalField: "signal-field",
} as const;
